### ISSUE TITLE
Allow `before_instance.valid_from` and `before_instance.valid_to` being equal?

### ISSUE THREAD

**Issue by ayumitamai97** [kufu/activerecord-bitemporal#59]
# Problem
`ActiveRecord::Bitemporal` does not accept `valid_to` which is equal to `valid_from`.

However, `valid_from` and `valid_to` **could ramdomly be equal**; **especially when the precision of `valid_from`and `valid_to` are relatively small like 4, or even 0** and tried to update a bitemporal record in a short period shorter than 1 second.

In such cases that `before_instance.valid_from == before_instance.valid_to` is true, `ActiveRecord::Rollback` is raised, and the new record will not be persisted.

```ruby
# lib/activerecord-bitemporal/bitemporal.rb:406
raise ActiveRecord::Rollback if before_instance.valid_from_cannot_be_greater_equal_than_valid_to 

# lib/activerecord-bitemporal.rb:89
def valid_from_cannot_be_greater_equal_than_valid_to                
  if valid_from && valid_to && valid_from >= valid_to               
    errors.add(:valid_from, "can't be greater equal than valid_to") 
  end                                                               
end                                                                 
```

# Solution I'd like
I would like activerecord-bitemporal to allow `valid_to` equal to `valid_from`.

But there would be unwanted side effects when accepting `valid_from` and `valid_to` with the exactly same values.
If so, could you please give me examples of possible side effects and close this issue?

Thank you!

**Comment by osyo-manga** [comment]
Thanks for issues :)

> However, valid_from and valid_to could ramdomly be equal; especially when the precision of valid_fromand valid_to are relatively small like 4, or even 0 and tried to update a bitemporal record in a short period shorter than 1 second.

I understand this problem.
However, I think allowing `valid_from = valid_to` for this reason is a bit dangerous.
For example, if there is `valid_from: 04/01 ~ valid_to: 04/01` data, you cannot refer to it with `Hoge.valid_at("04/01")`.
But it is referenced in `Hoge.ignore_valid_datetime`.
Also, if there are multiple `04/01 ~ 04/01`, order by `valid_from` may be undefined.

 ```ruby
company1 = Company.create!(name: "Company1")
company1.update_columns(valid_from: "04/01", valid_to: "04/01")

company2 = Company.create!(name: "Company2", bitemporal_id: company1.bitemporal_id)
company2.update_columns(valid_from: "04/01", valid_to: "04/01")

# not found records
p Company.valid_at("04/01").first
# => nil

# found `04/01 ~ 04/01` records
# but, order by `valid_from` may be undefined
p Company.ignore_valid_datetime.where(bitemporal_id: company1.bitemporal_id).order(:valid_from).pluck(:name)
# => ["Company1", "Company2"]
```

In this way, `valid_from = valid_to` data becomes noise unintentionally and becomes a burden on the user.
So I think we should carefully consider whether to allow `valid_from = valid_to`.

Is it possible to solve this problem by improving the time accuracy?

Thank you!

P.S. If you have a use case that requires `valid_from = valid_to` data, I think you should consider that you can optionally disable `validation` :)

**Comment by ayumitamai97** [comment]
I understand the possible issues.

> Is it possible to solve this problem by improving the time accuracy?

I could solved the problem by improving the time precision, though I'm coping with this in a different way.

Thank you!

**Comment by osyo-manga** [comment]
Thanks for issues! :)
